usgs/aqts-capture-ecosystem-switch

CHANGELOG.md
Jenkinsfile
README.md
code.json
package.json
serverless.yml
src/handler.py
src/utils.py
tests/test_handler.py

Turn on and off test and qa tier resources with a lambda (or something)
-----------
Add lambdas so the test and QA aurora db clusters can be automatically stopped outside of office hours.
https://internal.cida.usgs.gov/jira/browse/IOW-586
Description
-----------

Turn on and off test and qa tier resources with a lambda (or something) (IOW 586)

---

Jenkinsfile
src/utils.py

Title
-----------
Remove unused constants.  Update pipeline library to 2.2.0
Description
-----------

minor cleanup as per Andrew's feedback (IOW 586)

---

serverless.yml
src/handler.py
src/utils.py

Title
-----------
Description
-----------

Toggle test db

---

src/handler.py

Title
-----------
Description
-----------

fix typo that causes qa trigger to be enabled unexpectedly.

---

src/handler.py
tests/test_handler.py

Title
-----------
Description
-----------

disable db control lambda

---

serverless.yml

Title
-----------
Description
-----------

reenable schedule for test capture db

---

serverless.yml
src/utils.py

Title
-----------
Description
-----------

Fix typo stopping observations db

---

Dockerfile
Jenkinsfile
package.json
serverless.yml

Title
-----------
Description
-----------

IOW-651 Added support for deploying to DEV tier.

---

src/handler.py
src/rds.py

Title
-----------
Refactoring that was required for other stories changed the way we instantiate the RDS class.  The lambda function for stopping the observations db was not updated.   Update it so it pulls the connection info from the secrets manager.
Description
-----------

fix bug stopping observations db

---

Jenkinsfile
serverless.yml
src/db_resize_handler.py
src/handler.py

Title
-----------
Description
-----------
Change to PROD-EXTERNAL to conform to pattern of other projects

change PROD to PROD-EXTERNAL

---

serverless.yml

Title
-----------
Description
-----------

switch to the error-handler's invocation alarm

---

serverless.yml

Title
-----------
Change schedules for daylight savings
Description
-----------
Change minutes from 0 to 59.  If we change the hours from 23 to 0, it changes all the day boundaries and introduces room for errors.

fix stop start times for daylight savings

---

package-lock.json
package.json
requirements.txt
serverless.yml

Title
-----------
Description
-----------

add support of sending logs to elasticsearch

---

serverless.yml
src/db_resize_handler.py

Title
-----------
Description
-----------
Modify the grow and shrink state machines to pause for two minutes after the trigger is disabled and before resizing the db.

IOW-731 add pause between disable trigger and resize db

---

serverless.yml
src/handler.py
src/tests/test_handler.py

Title
-----------
Description
-----------
As part of IOW-717, I changed the KMS encryption key on the WMA-TEST and WMA-QA secrets.   In doing so, I inadvertently changed the permissions to read only.  So modify the policy for the new IOW-WQP-EXTERNAL-TEST and IOW-WQP-EXTERNAL-QA.

IOW-730 Make the WQP-EXTERNAL-TEST and WQP-EXTERNAL-QA secrets writable

---

serverless.yml
src/handler.py
src/subscriptions_handler.py
src/tests/test_subscriptions_handler.py

Title
-----------
Description
-----------
Created mailing lists inside secrets manager, which are managed by a lambda function that runs once a day.

IOW-744 Switch to using MS Team email addresses for SNS notifications

---

package.json
serverless.yml

Title
-----------
Description
-----------

add version pruning

---

serverless.yml

Title
-----------
Description
-----------

temp removal of cloudwatch event

---

serverless.yml

Title
-----------
Description
-----------

re-add cloudwatch event for controldbutil lambda

---

serverless.yml
src/db_resize_handler.py
src/handler.py
src/tests/test_handler.py

Title
-----------
After the circuit breaker returns to "all clear", increase db size to maximum and wait two hours before enabling trigger.
Description
-----------
Two hours would reduce bad cycling by about 90% relative to our current 10 minute bad cycling ...

IOW-755 Add delay and db resize after circuit breaker

---

README.md
serverless.yml
src/db_resize_handler.py
src/handler.py
src/tests/test_handler.py

Title
-----------
Description
-----------

Improve the README

---

src/handler.py

Title
-----------
Description
-----------

pretty confident that we don't need that test role

---

serverless.yml

Title
-----------
Description
-----------

IOW-781 add reserved concurrency

---

serverless.yml

Title
-----------
Description
-----------

changed tags

---

serverless.yml

Title
-----------
Description
-----------

remove duplicate tag

---

src/db_create_handler.py

Title
-----------
Description
-----------

added project_id tag

---

package-lock.json
package.json
serverless.yml
src/handler.py

Title
-----------
Description
-----------

new role and dependency update

---

Dockerfile
Jenkinsfile

Title
-----------
Description
-----------

IOW-745 replace dockerhub with ecr

---

Dockerfile
Jenkinsfile
package.json
serverless.yml
src/db_create_handler.py
src/tests/test_db_create_handler.py

Title
-----------
New observations db is unencrypted.  Update creation lambda to handle that.
Description
-----------
1.  Remove the copy snapshot step from the state machine to create the observations db.  It was only used to change encryption.
2.  Revert IOW-745 until the right docker image is available.

IOW-818 update lambda CreateObservationDb to handle an unencrypted db

---

serverless.yml
src/db_create_handler.py
src/db_resize_handler.py
src/handler.py
src/tests/test_utils.py
src/utils.py

Title
-----------
Description
-----------

IOW-822 Support new unencrypted capture db

---

src/utils.py

Title
-----------
Description
-----------

fix production dabase name typo

---

src/tests/test_utils.py
src/utils.py

Title
-----------
Description
-----------

Fix typo in new db name

---

serverless.yml

Title
-----------
Since QA dbs are created, used, and deleted, there should be no nightly shutdown for them.
Description
-----------

No QA db shutdowns
